### ISSUE TITLE
The mask is gone

### ISSUE THREAD

**Issue by xilanhu** [MehimoNemo/LethalCompanyShrinkRay#67] opened 2024-02-24 15:47 UTC
When you enter the game, your character's mask will appear normally, but when you die and settle, it will disappear.

Game Version:V49

Mod List.
AdvancedCompany
LCShrinkRay

Game Mode:LAN
![无标题](https://github.com/MehimoNemo/LethalCompanyShrinkRay/assets/51257868/6ee2cc45-68a4-427f-8fa3-a7ea01fdcffb)
![无标题1](https://github.com/MehimoNemo/LethalCompanyShrinkRay/assets/51257868/558f97de-1186-4f39-a8b5-cdfca1b9d40c)
[Player.log](https://github.com/MehimoNemo/LethalCompanyShrinkRay/files/14393388/Player.log)

**Comment by NiroDev** [comment] 2024-02-24 19:25
Hey, thank you very much for the detailed bug report!
I've got two more questions which may help solving this:
- Did the host or the client die?
- Was the person who lived grabbed by the person who died (due to velocity)?

**Comment by xilanhu** [comment] 2024-02-25 04:12
Hi, this is how I operate, I have tried many times and the problem can be reproduced
1. Open the game
2.LAN mode
3. Create and start the game (I'm the only player, I'm the host)
4. Select the default moon (41-Experimentation) pull the lever
5. Open the door of the ship in mid-air
6. Jump and die
7. Settle animation
8. Resurrect on the ship
9. Realize that the mask has disappeared

**Comment by NiroDev** [comment] 2024-02-29 15:38
Will be fixed in 0.4.0. Thanks a lot for reporting this issue and providing a detailed description on how to reproduce it!

**Closed by NiroDev** 2024-02-29 15:38 UTC
Labels: Urgent
