### ISSUE TITLE
[Ver 1.0.1] Some Issues/Feedback/Question

### ISSUE THREAD

**Issue by CoolLKKPS** [MehimoNemo/LethalCompanyShrinkRay#66] opened 2024-02-22 12:53 UTC
thread

**Comment by CoolLKKPS** [comment] 2024-02-22 13:02
keep up the good work! really enjoy ur creation

**Comment by CoolLKKPS** [comment] 2024-02-22 19:11
change some information, to make this issues report not conflict with mod config
btw should allow LC_CustomDifficulty change player body size too

**Comment by NiroDev** [comment] 2024-02-23 16:26
1. Current solution for enlarging is temporary and will change in the near future, likely through UI with mode selection

2. Good suggestion, but a little bit lower in priority currently. Will keep that in mind in my way towards 0.4.0

3. Good solution for single player, will keep it in mind

4. Weird, I always test in Lan mode. Do you have a logoutput from it?

5. The only one I don't fully agree with, as the gun is overall still a regular item

**Comment by NiroDev** [comment] 2024-02-23 16:27
Our team member who implemented a terminal fix, which is currently buggy, will be back next week. Will let her know about it. Noticed it in our testing too. Sorry for the inconvenience

**Comment by CoolLKKPS** [comment] 2024-02-23 17:24
aha, i knew it, thx for the reply
so i like those ideas from this mod that's so funny, previously we (i mean my team members), tried of 3 mods: LC_CustomDifficulty can go big or small, that can make easier or harder to avoid gunshot, but LC_CustomDifficulty is buggy bc they forgot to upgrade, have dropship and sound glitch issues; LC_Midgets only can go small, it just a simple mod to change body size, not fix visual issues at all; another little company did try to fix that, but no it just shaking when using terminal, so yea... for now no any mod can done so far, and the real good reason i like this mod is, everyone can share ideas in here, i can contact u by using github
and the LAN issues, i will try again, not sure about this issue, maybe i have to load the mod for once in online mode (in LAN mode i can't even buy that ray gun)

**Comment by CoolLKKPS** [comment] 2024-02-23 17:33
it did add ray gun item in store when in the online mode, so i guess i have to go online mode and then go offline mode

**Comment by NiroDev** [comment] 2024-02-23 21:33
Will try my best to make this mod deliver everything that the other mods were able to do, where time allows / possible. Your ideas are always welcome. I'm more active on discord though (niro1996), but shared ideas from here will be noticed and considered too.
One advice for the future, for better organization would be to split the issues into several ones, instead of one post containing a list of issues & suggestions. that way i can respond to each individually and easily mark them as resolved once done. Would be appreciated for future posts :)
Not a critic though, more of an advice. I really value your feedback!

**Comment by CoolLKKPS** [comment] 2024-02-23 21:44
uh im not active on Discord, but im apologize about that title, idk what i think at that moment, but i don't really want to create many more issues in github, even i still love to help the community

**Comment by CoolLKKPS** [comment] 2024-02-28 16:17
add something in the first post, u can see the changelog, in short: Configurable some feature, Compatible for a mod

**Comment by NiroDev** [comment] 2024-02-29 14:14
Working on 0.4.0 currently, which adds "Light & Heavy Potions" to cover singleplayer. They will be configurable and available in store & as scrap. Also adds a lot of other things. I'm always searching for active beta testers for the mod. If that's something you're interested in, then i can add you as a beta tester on [our discord](https://discord.gg/63KdxhQ2Dn). Posted the first beta for 0.4.0 there today.

**Comment by CoolLKKPS** [comment] 2024-02-29 17:56
So my email is start with PSKyle, outlook email, will try to create a new email address for public

**Comment by CoolLKKPS** [comment] 2024-02-29 17:57
and i was playing modpack with my friend, sorry take too long for reply

**Comment by CoolLKKPS** [comment] 2024-02-29 18:03
uh can't use every google stuffs in china, the best way is using OneDrive or just send email via Outlook

**Comment by CoolLKKPS** [comment] 2024-03-01 14:24
@NiroDev 
ok uh well...
1. ScanNode didn't correct to point at the shrink player
2. [MANY BUG] if held player grab one or more items, the player who hold the shrink player weight won't changed, i sug held player won't able to interact anything:
> ## If true, held players can able to interact, causing some comedic, but game breaking effects.
> # Setting type: Boolean
> # Default value: false
> FriendlyFlight = false
3. Should prevent picking up the player during the shrink process, and should check if there have enough space or not
 - the issue only happen when as client, try to picking up the player during the shrink process will stuck the player who being held

**Comment by CoolLKKPS** [comment] 2024-03-01 15:01
will change title and first post content after i done of the test

**Comment by CoolLKKPS** [comment] 2024-03-01 16:16
@NiroDev ok wait for new update now, currently many issues so yea...

**Comment by NiroDev** [comment] 2024-03-01 16:27
Thanks for the detailled testing. I'll respond in detail later.
The weight isn't changing yet for held players. That's planned for one of the next versions.

**Comment by CoolLKKPS** [comment] 2024-03-01 16:29
uh i found another bug...

**Comment by NiroDev** [comment] 2024-03-01 20:23
Regarding your list:

1 - Fixed being able to scan yourself. The offset is still to be done.
6 - That's intended as of now, since there's a lot happening when someboday dies. Will require more work to make this possible.
8 - Will look into that one soonish, as it was reported multiple times now. One of the tougher things to fix

**Comment by CoolLKKPS** [comment] 2024-03-01 21:58
add some feedback and change issue 3,6,9

**Comment by CoolLKKPS** [comment] 2024-03-02 11:09
@NiroDev u might need [CSync](https://thunderstore.io/c/lethal-company/p/Owen3H/CSync) to deal with issue 3

**Comment by NiroDev** [comment] 2024-03-02 11:16
Thought about using networkVariable but likely the solution is much easier. Assumed that csync was only for config syncing, which I already do manually. Will switch to csync in a free minute though, once it's out for longer

**Comment by NiroDev** [comment] 2024-03-03 06:45
Also noticed the missing cosmetics in our testing yesterday, but not sure yet if it's caused from our side. Did it happen with the 0.4.0 beta, or with the latest Thunderstore version of LittleCompany? Could do a quick test later today to check if any changes from our side are causing this

**Comment by CoolLKKPS** [comment] 2024-03-03 11:02
ok
________________________________

**Comment by CoolLKKPS** [comment] 2024-03-03 23:53
confirm, modpack issues, but i found another bug btw

**Comment by NiroDev** [comment] 2024-03-04 12:00
oh, that one was an oversight, which should affect the scrap value and not the store value.
For example if the store value is 100, then the scrap value shouldn't go above that to prevent people from buying them for less than their sell actual value.
Should be fixed now :)

**Comment by NiroDev** [comment] 2024-03-05 10:03
Worked a bit more on it:
- Scan node value & weight of grabbable players updating correctly
- Shrink Ray cooldown fully working now

**Comment by CoolLKKPS** [comment] 2024-03-05 21:40
add another feedback in first post: u can set this mod as dependency: https://thunderstore.io/c/lethal-company/p/Rune580/LethalCompany_InputUtils

**Comment by CoolLKKPS** [comment] 2024-03-09 21:14
new issues for release version:
1. cosmetics won't go small
2. if A player joining but B player already shrunken, in A player view B player are still normal size

**Comment by CoolLKKPS** [comment] 2024-03-09 23:34
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LCShrinkRay.helper.PlayerInfo.get_CurrentPlayerID () (at <0cf3669530bb4845b875a2554f0a985c>:IL_0005)
LCShrinkRay.patches.ScreenBlockingGrabbablePatch.GrabItem (GrabbableObject __instance) (at <0cf3669530bb4845b875a2554f0a985c>:IL_0022)
(wrapper dynamic-method) GrabbableObject.DMD<GrabbableObject::GrabItem>(GrabbableObject)
GrabbableObject.GrabClientRpc () (at <af9b1eec498a45aebd42601d6ab85015>:IL_00C4)
GrabbableObject.__rpc_handler_1334815929 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <af9b1eec498a45aebd42601d6ab85015>:IL_002E)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkMessageManager:ReceiveMessage(FastBufferReader, NetworkContext&, NetworkMessageManager)
Unity.Netcode.NetworkMessageManager:HandleMessage(NetworkMessageHeader&, FastBufferReader, UInt64, Single, Int32)
Unity.Netcode.NetworkMessageManager:ProcessIncomingMessageQueue()
Unity.Netcode.NetworkManager:NetworkUpdate(NetworkUpdateStage)
Unity.Netcode.NetworkUpdateLoop:RunNetworkUpdateStage(NetworkUpdateStage)
Unity.Netcode.<>c:<CreateLoopSystem>b__0_0()

**Comment by CoolLKKPS** [comment] 2024-03-09 23:51
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::GrabObjectClientRpc>(GameNetcodeStuff.PlayerControllerB,bool,Unity.Netcode.NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_2552479808 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <af9b1eec498a45aebd42601d6ab85015>:IL_0064)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkMessageManager:ReceiveMessage(FastBufferReader, NetworkContext&, NetworkMessageManager)
Unity.Netcode.NetworkMessageManager:HandleMessage(NetworkMessageHeader&, FastBufferReader, UInt64, Single, Int32)
Unity.Netcode.NetworkMessageManager:ProcessIncomingMessageQueue()
Unity.Netcode.NetworkManager:NetworkUpdate(NetworkUpdateStage)
Unity.Netcode.NetworkUpdateLoop:RunNetworkUpdateStage(NetworkUpdateStage)
Unity.Netcode.<>c:<CreateLoopSystem>b__0_0()

**Comment by CoolLKKPS** [comment] 2024-03-10 00:07
![1710029200253](https://github.com/MehimoNemo/LethalCompanyShrinkRay/assets/96377775/7c95f2e9-c7e1-4d18-b510-393d6c25d7b4)

**Comment by CoolLKKPS** [comment] 2024-03-10 00:07
and still can moveable

**Comment by NiroDev** [comment] 2024-03-10 11:30
Will look into them right after the holidays, if they aren't solved by then. Thanks for reporting, it really helps me a lot!

**Comment by CoolLKKPS** [comment] 2024-03-10 21:29
lol actually i found another bug, u just need to jump and look down, and u can see the tooltip call "grab", even u can't grab urself, but that definitely funny hahahahahahaha

**Comment by NiroDev** [comment] 2024-03-12 19:30
The error from your log got fixed in 0.4.5

**Comment by CoolLKKPS** [comment] 2024-03-13 23:57
will test that again :)

**Comment by CoolLKKPS** [comment] 2024-03-16 21:57
so about released ver 0.4
store item and scrap item should not use the same ID, i sug scrap item name will start with "old" word
and now u did can grab urself lol

still need sometime to test 0.5
i very agree u increase the price of heavy potion, but i still need more test

**Comment by CoolLKKPS** [comment] 2024-03-16 21:59
store items should not have value, otherwise will make reach the quota more easier

**Comment by NiroDev** [comment] 2024-03-19 07:36
Fixed the "host is able to grab themself". Was an oversight where the Trigger was enabled in the Start method. Covered that and any other cases.
Will push a new beta in around 8h

**Comment by CoolLKKPS** [comment] 2024-03-19 08:26
nice!

**Comment by CoolLKKPS** [comment] 2024-03-19 21:52
btw i like this idea #61
but switch to third person will break something, like u might can see directly the ghost girl even that should not render

**Comment by NiroDev** [comment] 2024-03-22 12:04
New thunderstore beta version is out: https://thunderstore.io/c/lethal-company/p/Toybox/ToyboxBetaTest/
This one fixes the weightMultiplier aswell as a few other things, that are mentioned in the Changelog tab of the linked page

**Comment by CoolLKKPS** [comment] 2024-03-24 00:42
got it, but will need sometime to relax, need to take some break, its not too hurry right?

**Comment by CoolLKKPS** [comment] 2024-03-24 00:43
will back after tuesday in nxt week

**Comment by NiroDev** [comment] 2024-03-24 14:04
No worries, take the time you need and don't see it as mandatory :)

**Comment by CoolLKKPS** [comment] 2024-03-26 08:45
uh just a suggestion, update the beta version too, so i don't need to update my modpack very often
________________________________

**Comment by CoolLKKPS** [comment] 2024-03-26 09:07
ok, u can check my modpack here, actually i will update this modpack daily: https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h?e=cX6g0c

**Comment by NiroDev** [comment] 2024-03-26 14:44
Will keep the beta one also up to date. Pushed it to 0.5.2 aswell right now. Thanks for the suggestion :)

**Comment by CoolLKKPS** [comment] 2024-03-27 06:08
@NiroDev im not sure why config file are still stay in the old version, will use release version instead the beta version

**Comment by NiroDev** [comment] 2024-03-27 06:24
have you started the game after updating, as the config is written on start?

**Comment by CoolLKKPS** [comment] 2024-03-27 06:28
uh actually i compare between beta and release, and find out release version config are newer than beta version, so i choose to use release version instead

**Comment by CoolLKKPS** [comment] 2024-03-28 00:39
@NiroDev there has many problem i think
1. if player size is 0.2, use vent sometime will go into the void
2. can't escape grab sometime (when in the company)
3. using ladder and someone try to grab when in shrunken, will break something
4. tooltip sometime will display "escape grab" even not been grabbed
5. heavy potion can't go Big
6. Still cannot remember the player size after dead
7. should limit the min. shrink size, player can't go small below this value size
8. de-sync, idk how but sometime normal size player can have shrunken player movement speed

**Comment by CoolLKKPS** [comment] 2024-03-28 00:42
also i saw some error related this mod in the log, im not sure bc im updating my modpack to decrease the difficulty

**Comment by NiroDev** [comment] 2024-03-28 05:04
6. is planned for 0.6.0. will look into the others during the next week

**Comment by CoolLKKPS** [comment] 2024-03-28 05:06
i will start testing after about 1-2 hours with my friends, modpack are updated

**Comment by NiroDev** [comment] 2024-03-28 05:08
Thanks for testing :) I may not always express this enough, but it really helps me/us making this mod more stable

**Comment by CoolLKKPS** [comment] 2024-03-28 06:15
additional:
1. when u try to go down by using ladder, the position is not aligned, for example use ladder in the company building
2. u can drink the potion while still shrinking, that not only cause view de-sync i think
3. will lose all the potion after reload the savefile

**Comment by CoolLKKPS** [comment] 2024-03-28 06:49
i think some issues cause bc since u tried to fix host can grab themself, u changed some position things, i sug don't change too much

**Comment by NiroDev** [comment] 2024-03-28 08:36
Half of them should've existed earlier already but remained unnoticed, while the other half may be caused by some reworks lately, where I changed some parts in preparation of enemy & object shrinking, which is now way easier to do than before and likely coming rather sooner than later.
The next big update will contain more fixes than features to have a more or less stable base to continue working on. I will take a detailed look at all of the issues next week.

Also got two people that help me with coding now, who currently
- fix players arm offset
- ModelReplacementAPI compatibility
- glitching/shaking for grabbable/held players
So that I can focus on bugfixing :)

**Comment by NiroDev** [comment] 2024-03-29 20:05
I will update this message when i make progress. It's related to the bugs you found. Once i fixed them i'll push out 0.5.4
1. fixed with workaround
2. tbd
3. tbd
4. tbd
5. can't reproduce so far. maybe limited by config during your tests? (default size change is 0.4, which makes it 1 -> 1.4 -> 1.8. but max is 1.7, so last won't work)
6. postponed to 0.6.0
7. can be configurated
8. tbd
9. tbd
10. fixed
11. attempt to fix, needs more testing by us

**Comment by CoolLKKPS** [comment] 2024-03-31 03:05
just let u know, "tiny_company" mod are perfectly fixed the terminal view issues, u might need to ask that author so that if player go big, they won't need to worry about terminal view issues again
and "tiny_company" mod not work with vanilla If not hosting the game, if u can contact that author, u can do me a favor to mention this issues

**Comment by NiroDev** [comment] 2024-03-31 09:34
This mod should have fixed the terminal too. Or is the other mods doing it better in some way? Haven't looked into it yet :)

**Comment by CoolLKKPS** [comment] 2024-03-31 09:36
yes that mod do more better i think, still working on my modpack bc i found many issues when i try to add more gameplay

**Comment by CoolLKKPS** [comment] 2024-03-31 09:38
oh and, still can cause terminal view issues if go big

**Comment by CoolLKKPS** [comment] 2024-03-31 10:38
> attempt to fix "Ungrab : [E]" being displayed while not grabbed

uh is "Escape Grab: Space"

**Comment by NiroDev** [comment] 2024-03-31 19:36
Took a quick look at the Tiny_Company mod and it just changes the player scale back to normal while being at the terminal.
While this won't update the players position from the pov of others, it works well for the player who uses it.
I will consider to use this as a temporary solution till we find the time to work out something better (e.g. adding small stairs below for shrunken players / crouching for enlarged ones)

**Comment by CoolLKKPS** [comment] 2024-04-01 02:48
nice, btw v50 beta has released, so i will do some test in there!

**Comment by NiroDev** [comment] 2024-04-01 06:57
That's great! Curious how compatible it will be

**Comment by NiroDev** [comment] 2024-04-06 07:02
Pushed 0.5.7, which is compatible with v50

**Comment by CoolLKKPS** [comment] 2024-04-06 07:06
actually... LethalLib still not useable, enemies can't spawn in the game so... still need to wait

**Comment by NiroDev** [comment] 2024-04-06 09:15
They fixed that today with 0.15.1

**Comment by NiroDev** [comment] 2024-04-06 09:20
Scopophobia and some other custom enemy mods still break enemy spawning though. There has been a change to the LineOfSight method. Has been renamed and therefore some mods that use it throw errors now very early, causing enemy spawning to break

**Comment by CoolLKKPS** [comment] 2024-04-06 09:56
u r correct, working on it

**Comment by CoolLKKPS** [comment] 2024-04-09 19:41
@NiroDev ok so planned to test after 2-4 days
also i got a feedback, so if tiny player can load-in to and launch by using a shotgun, that's comedic

**Comment by CoolLKKPS** [comment] 2024-04-09 19:41
v50 are really fun for me, took a bit long >:D

**Comment by CoolLKKPS** [comment] 2024-04-14 18:33
0.5.8:
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LittleCompany.components.GrabbablePlayerObject.Update () (at <03aeb5df03c4438da6d928024586172a>:IL_00D9)

u have to add grab/escape cooldown, otherwise the game will have more de-sync
and also still not remember the body size, after respawn they will restore to normal size, but if u try to shrink the player, they will start with the size that previous have

**Comment by CoolLKKPS** [comment] 2024-04-14 20:43
start testing v0.6 at tomottow

**Comment by CoolLKKPS** [comment] 2024-04-14 20:48
@NiroDev ok v50 have huge issues about `grabInvalidated` status, this is very very frustrating, and i have to remind u, u need to add cooldown and that's really necessary

**Comment by CoolLKKPS** [comment] 2024-04-15 00:05
also when u click mouse midbutton, user can trigger shrinkray targeting, a glitch

**Comment by NiroDev** [comment] 2024-04-17 09:36
> @NiroDev ok v50 have huge issues about `grabInvalidated` status, that's very very frustrating, and i have to remind u, u need to add cooldown and that's really necessary

I would prefer to fix the issues as good as possible before going for a cooldown for grabbing/escaping. Will take a more detailed look at this behaviour in the next days. 

The ToyboxBetaTest mod is now at 0.6.3, which contains more content such as enemy and item scaling, enemy events on death-shrinking, being able to grab smaller players even as an enlarged player, new options and more. We aim to make this one our 1.0 release so we will pay more attention to stability during development and before publishing it.

Sorry for the inconvenience with the grabbing bug and thank you for reporting it!

**Comment by CoolLKKPS** [comment] 2024-04-17 21:27
I probably won't test death-shrinking feature since i disable that before, but will do some quick test in the nxt few days, but still im not sure why need to shrink enemies...

**Comment by CoolLKKPS** [comment] 2024-04-18 00:37
@NiroDev BUG:
if u use shovel to hit the shrink player twice, they not only to be flat, but also change the size to very tiny, but there's many problem: first the raygun or potion still keep start at original size to the target size (just like 0.5.7 the mod won't check the current player body size, when player dead, revive, etc.); second very tiny size will glitch if player not land on the ground. for me those 2 issues are already many

**Comment by CoolLKKPS** [comment] 2024-04-18 20:46
3. u need to fix the offset for held player view, when shrunk player body size are too low

**Comment by NiroDev** [comment] 2024-04-20 07:34
Hey, first of all: thanks again for testing! 
The 0.6.3 of ToyboxBetaTest was mainly for a quick test of the enemy events. A few of the bugs it contained, such as the item offset, has been fixed in 0.6.4.

We implemented enemy shrinking to make the shrink ray useful outside the ship, as it felt like it had a very stale use, where we only grabbed it for shrinking us and the rest of the round it remained in the ship. That made the item a bit boring compared to other options, such as potions, which do the same. 

So after shoveling twice they keep the tiny size? Or is the animation that makes them temporary very tiny an issue? I will check that today.

The "very tiny player been stuck" bug happened yesterday too, but I assumed it happened because I got thrown between two pallets. If it happens again then I'll check the log in detail to see what could cause this behaviour. Will tell my friends to grab and throw each other around more often today :)

**Comment by NiroDev** [comment] 2024-04-20 07:37
One last addition: the deathshrinking config will only count for players, as it's far more annoying  when playing with randoms and I assume mostly unwanted. Items and enemies can always be shrunken to death

**Comment by AboveFire** [comment] 2024-04-20 14:14
Tbh, both item shrinking an monster shrinking could have a high level flag disabling them (just remove the layer mask in the raycast of the gun)
It's not really something I would want to use but I could see people wanting to play mostly vanilla but shrunk?

**Comment by CoolLKKPS** [comment] 2024-04-21 00:32
i more agree with item shrinking and monster shrinking can be disabled individually, to optional choose which can able to shrinking

**Comment by CoolLKKPS** [comment] 2024-05-02 22:24
@NiroDev so after recently beta update, i sug raygun price set to 1k-2k, and i think this version is ready to release, so will close this ticket temporary til i found more issues

**Comment by CoolLKKPS** [comment] 2024-05-07 02:23
@NiroDev Log Conflict with LogNeuter
so in vanilla game, u will see some trash logs similar like:
Targetable A
Setting animation on client

and if u install LogNeuter, u can see this is from `[EnemyAI|PlayerIsTargetable]` and `[GameNetcodeStuff.PlayerControllerB|IsInSpecialAnimationClientRpc]`, but this mod will cause LogNeuter to made no changes to that method, this is a big conflict and will stop people diagnosing by seeing logs

**Comment by CoolLKKPS** [comment] 2024-05-07 02:24
Setting animation on client can trigged by swing the shovel

**Comment by AboveFire** [comment] 2024-05-07 14:39
With and without logNeuter I can see the "Setting animation on client" log. I can also see it when removing LittleCompany. I'm not sure what's the expected behavior since I don't usually have logNeuter. Do I need a particular config on logNeuter to see this?

**Comment by CoolLKKPS** [comment] 2024-05-07 21:48
[BlueAmulet.LogNeuter.zip](https://github.com/MehimoNemo/LethalCompanyShrinkRay/files/15241425/BlueAmulet.LogNeuter.zip)
@AboveFire

**Comment by CoolLKKPS** [comment] 2024-05-07 21:50
u will see the huge different if with this cfg, that actually took me so much time to do, u **might** will like to use this to debuging

**Comment by CoolLKKPS** [comment] 2024-05-12 01:46
@NiroDev another conflict confirmed

**Comment by CoolLKKPS** [comment] 2024-05-12 02:01
first, conflict with Rosie **Moon**pack, when playing "Summit" moon, at the beginning u will receive those logs and my game will crash.

[Message:Toybox.LittleCompany] Enemy shrunken to death
[Message:Toybox.LittleCompany] Spawn enemy.
[Message:Toybox.LittleCompany] DoublewingedBird(Clone) event handler has awaken!
[Message:Toybox.LittleCompany] Spawned enemy Manticoil at position (92.42, -33.34, 7.52)
[Message:Toybox.LittleCompany] Spawn enemy.
[Message:Toybox.LittleCompany] DoublewingedBird(Clone) event handler has awaken!
[Message:Toybox.LittleCompany] Spawned enemy Manticoil at position (31.16, 15.97, 80.62)
[Message:Toybox.LittleCompany] EnemyEventManager.PlayerCount: 1
[Message:Toybox.LittleCompany] Syncing the death shrink event took 0 frames.
[Info   : Unity Log] Kill enemy server rpc called with destroy True
[Info   : Unity Log] Kill enemy called; destroy: True
[Info   : Unity Log] Despawn network object in kill enemy called!

i don't even activate "Enemy shrunken to death" feature actually

**Comment by CoolLKKPS** [comment] 2024-05-12 02:10
second idk how burning toy robot works, maybe it doesn't support being spawned for now, but i did see burning toy robot spawn outside naturally when playing "Summit" moon, and can damage me really far away (really sus that was a glitch only trigger when the game are lagging)

**Comment by CoolLKKPS** [comment] 2024-05-12 02:12
but other moons like "starlancer moon" etc. doesn't have those 2 issues, so maybe, just maybe that cause by moon author, but just in case that seems like a potential problems

**Comment by CoolLKKPS** [comment] 2024-05-12 02:55
@NiroDev 1.0.1 cannot playable for me, that feature affect too many i think

**Comment by CoolLKKPS** [comment] 2024-05-14 11:14
@NiroDev @AboveFire another issue in 1.0.0, the enemy behavior not correct as what i set in the config, and only affect hoarding bug, they always won't flying no matter the player size are smaller than itself (on the code side actually), this issue is getting real old now, what i expect is, hoarding bug only grab smaller player, and once they grab the player, they won't drop the player

**Closed** 2024-05-16 16:17 UTC
Labels: Thread
